export default {
  zeno: [
    "We have two ears and one mouth, so we should listen more than we say.",
    "Man conquers the world by conquering himself.",
    "A friend is our alter ego.",
    "All the good are friends of one another.",
    "We have two ears and one mouth, therefore we should listen twice as much as we speak.",
    "Well-being is attained little by little, and nevertheless is no little thing itself.",
    "if being is many, it must be both like and unlike, and this is impossible, for neither can the like be unlike, nor the unlike like",
    "The goal of life is living in agreement with Nature.",
  ],
  clenthes: [
    "The Fates guide the person who accepts them and hinder the person who resists them.",
    "Ignorant men differ from beasts only in their figure.",
    "Lead me, Zeus, and you, Fate, wherever you have assigned me. I shall follow without hesitation; but even if I am disobedient and do not wish to, I shall follow no less surely.",
  ],
  chrysippus: [
    "If I had followed the multitude, I should not have studied philosophy.",
    "There is a certain head, and that head you have not. Now this being so, there is a head which you have not; therefore, you are without a head.",
    "Death is the separation of soul from body.",
    "Vice cannot be removed completely, nor is it right that it should be removed.",
    "Every animal is related to its own constitution and the consciousness of it.",
    "I myself think that the wise man meddles little or not at all in affairs and does his own things.",
  ],
  seneca: [
    "Luck is what happens when preparation meets opportunity.",
    "All cruelty springs from weakness.",
    "Begin at once to live, and count each separate day as a separate life.",
    "Throw me to the wolves and I will return leading the pack.",
    "They lose the day in expectation of the night, and the night in fear of the dawn.",
    "Every night before going to sleep, we must ask ourselves: what weakness did I overcome today? What virtue did I acquire?",
    "Difficulties strengthen the mind, as labor does the body.",
    "Associate with people who are likely to improve you.",
    "Man is affected not by events but by the view he takes of them.",
    "We suffer more often in imagination than in reality.",
    "Time heals what reason cannot.",
    "Hang on to your youthful enthusiasms — you’ll be able to use them better when you’re older.",
    "It is not the man who has too little, but the man who craves more, that is poor.",
    "It is the power of the mind to be unconquerable.",
    "The bravest sight in the world is to see a great man struggling against adversity.",
    "He suffers more than necessary, who suffers before it is necessary.",
    "Life is never incomplete if it is an honorable one. At whatever point you leave life, if you leave it in the right way, it is whole.",
  ],
  epictus: [
    "Wealth consists not in having great possessions, but in having few wants.",
    "Don't explain your philosophy. Embody it.",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power or our will.",
    "Man is not worried by real problems so much as by his imagined anxieties about real problems.",
    "First say to yourself what you would be; and then do what you have to do.",
    "It's not what happens to you, but how you react to it that matters.",
    "If you want to improve, be content to be thought foolish and stupid.",
    "Any person capable of angering you becomes your master;he can anger you only when you permit yourself to be disturbed by him.",
    "He who laughs at himself never runs out of things to laugh at.",
    "Circumstances don't make the man, they only reveal him to himself",
    "It is impossible for a man to learn what he thinks he already knows.",
    "People are not disturbed by things, but by the views they take of them.",
    "Only the educated are free.",
    "You are a little soul carrying around a corpse",
    "To accuse others for one's own misfortune is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete.",
    "First learn the meaning of what you say, and then speak.",
    "No man is free who is not master of himself.",
  ],
  marcus: [
    "You have power over your mind - not outside events. Realize this, and you will find strength.",
    "The happiness of your life depends upon the quality of your thoughts.",
    "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",
    "Waste no more time arguing about what a good man should be. Be one.",
    "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love ...",
    "The best revenge is to be unlike him who performed the injury.",
    "The soul becomes dyed with the colour of its thoughts.",
    "It is not death that a man should fear, but he should fear never beginning to live.",
    "Our life is what our thoughts make it.",
    "If it is not right do not do it; if it is not true do not say it",
    "The best revenge is not to be like your enemy.",
    "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.",
  ],
};
